# 数据路径配置
data:
  # 数据样本目录
  directory: "/data_3/aiak_pretrain_data_5M_vqa"
  # 存储配对文件名的临时文件
  output_base: "base_name_v2_vqa_pretrain_5M_16k.txt"
  # 最终输出文件（包含token长度信息）
  output_token: "token_info_v2_vqa_pretrain_5M_16k.txt"

# 模型路径
model:
  checkpoint: "/vlm/xiangan/pretrain_models/rice_vl/rice_vl_rice_300m_qwen2.5_7b_adapter_v1_fixed_tokenizer_huggingface"

sample:
  # 训练数据的最大长度
  max_len: 16384
  # 决定解析方式
  task_type: sft 
  max_prompt: null
  max_answer: null

# 图像处理参数
image:
  min_pixels: 3136   # 4*28*28
  max_pixels: 8294720 # 10580*28*28(8294720,16384)
  # 最大宽高比限制（超过此值的图片将被过滤）,这是隐含信息（qwen vl自己处理）
  max_aspect_ratio: 200

# 并行处理参数
processing:
  # 每个进程处理的样本块大小
  chunk_size: 5000
  # 归并参数（排序），每N个stage0文件合并为1个stage1文件
  stage1_merge_chunk: 20
  n_workers: 64
  # 线程池最小线程数
  min_workers: 10
  # 线程池最大线程数
  max_workers: 32
  # 超时设置（根据数据量定，1M数据按 45分钟(2700s)估算）
  time_out: 20000

# 日志与临时文件
logging:
  # 日志级别（DEBUG, INFO, WARNING, ERROR, CRITICAL）
  level: "INFO"
  # 日志文件路径
  file: "./logs/s1_processing_vqa_pretrain_5M_16k.log"
  # 是否使用 /dev/shm 作为临时目录
  use_shm: true
