# 数据路径配置
data:
  # Sample Data Directory
  directory: "/vlm/xiangan/datasets/aiak_caption_emova_300k"
  # Temporary file that stores paired filenames
  output_base: "base_name_captions.txt"
  # Final Output File (with token length information)
  output_token: "token_info_captions.txt"

# model path
model:
  checkpoint: "/vlm/xiangan/pretrain_models/rice_vl/rice_vl_rice_300m_qwen2.5_7b_adapter_v1_fixed_tokenizer_huggingface"

sample:
  # packed-sample's max-length
  max_len: 8192
  # parsing method
  task_type: pretrain 
  max_prompt: null
  max_answer: null

# image preprocessing parameters
image:
  min_pixels: 3136   # 4*28*28
  max_pixels: 4014080 # 5120*28*28(4014080,8192)
  # Maximum aspect ratio limit
  max_aspect_ratio: 200

# Parallel processing parameters
processing:
  # Chunk size per process
  chunk_size: 5000
  # Merge parameter (sorted): combine every N stage-0 files into one stage-1 file.
  stage1_merge_chunk: 10
  n_workers: 64
  # Minimum thread-pool size
  min_workers: 10
  # Maximum threads in the thread pool
  max_workers: 32
  # Timeout: ~45 min (2 700 s) per 1 M samples, scale with data volume.
  time_out: 20000

# Logs and temporary files
logging:
  # Log Level（DEBUG, INFO, WARNING, ERROR, CRITICAL）
  level: "INFO"
  # Log file path
  file: "./logs/s1_processing_captions_pretrain_emova_300k_8k.log"
  # Whether to use /dev/shm as the temporary directory
  use_shm: false
